const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('mdview', {
  pasteImage: bytes => ipcRenderer.invoke('paste-image', bytes),
  getLinkIcon: target => ipcRenderer.invoke('link-icon', target),
  getMenuBar: () => ipcRenderer.invoke('get-menu-bar'),
  popupMenu: (index, point) => ipcRenderer.invoke('popup-menu', index, point),
  quickAction: action => ipcRenderer.invoke('quick-action', action),
  setQuickActions: actions => ipcRenderer.invoke('set-quick-actions', actions),
  onQuickActionsChanged: callback => ipcRenderer.on('quick-actions-changed', (_event, actions) => callback(actions)),
  onMenuStateChanged: callback => ipcRenderer.on('menu-state-changed', (_event, state) => callback(state)),
  onActivateMenuBar: callback => ipcRenderer.on('activate-menu-bar', (_event, index) => callback(index)),
  workspaceView: payload => ipcRenderer.send('workspace-view', payload),
  draft: payload => ipcRenderer.send('draft', payload),
  menuState: state => ipcRenderer.send('menu-state', state),
  onMenuAction: callback => ipcRenderer.on('menu-action', (_event, action, value) => callback(action, value)),
  save: payload => ipcRenderer.invoke('save', payload),
  preview: payload => ipcRenderer.invoke('preview', payload),
  onSaved: callback => ipcRenderer.on('saved', (_event, value) => callback(value)),
  onBusy: callback => ipcRenderer.on('file-busy', (_event, value) => callback(value)),
  onSaveRequest: callback => ipcRenderer.on('save-request', (_event, value) => callback(value)),
  onToggleEdit: callback => ipcRenderer.on('toggle-edit', () => callback()),
  onEditError: callback => ipcRenderer.on('edit-error', (_event, value) => callback(value)),
  open: () => ipcRenderer.invoke('open'),
  newDocument: () => ipcRenderer.invoke('new-document'),
  switchTab: payload => ipcRenderer.invoke('switch-tab', payload),
  closeTab: payload => ipcRenderer.invoke('close-tab', payload),
  onTabs: callback => ipcRenderer.on('tabs', (_event, value) => callback(value)),
  onCloseTabRequest: callback => ipcRenderer.on('close-tab-request', () => callback()),
  onNextTabRequest: callback => ipcRenderer.on('next-tab-request', () => callback()),
  onPreviousTabRequest: callback => ipcRenderer.on('previous-tab-request', () => callback()),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getI18n: () => ipcRenderer.invoke('get-i18n'),
  setLanguage: language => ipcRenderer.invoke('set-language', language),
  onLanguageChanged: callback => ipcRenderer.on('language-changed', (_event, language) => callback(language)),
  chooseSaveDirectory: () => ipcRenderer.invoke('choose-save-directory'),
  resetSaveDirectory: () => ipcRenderer.invoke('reset-save-directory'),
  drop: file => ipcRenderer.invoke('drop', webUtils.getPathForFile(file)),
  reload: () => ipcRenderer.invoke('reload-document'),
  external: href => ipcRenderer.invoke('external', href),
  copy: text => ipcRenderer.invoke('copy', text),
  onDocument: callback => ipcRenderer.on('document', (_event, result) => callback(result)),
  onToggleOutline: callback => ipcRenderer.on('toggle-outline', () => callback())
});
