const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('mdview', {
  draft: payload => ipcRenderer.send('draft', payload),
  save: payload => ipcRenderer.invoke('save', payload),
  preview: payload => ipcRenderer.invoke('preview', payload),
  onSaved: callback => ipcRenderer.on('saved', (_event, value) => callback(value)),
  onBusy: callback => ipcRenderer.on('file-busy', (_event, value) => callback(value)),
  onSaveRequest: callback => ipcRenderer.on('save-request', (_event, value) => callback(value)),
  onToggleEdit: callback => ipcRenderer.on('toggle-edit', () => callback()),
  onEditError: callback => ipcRenderer.on('edit-error', (_event, value) => callback(value)),
  open: () => ipcRenderer.invoke('open'),
  newDocument: () => ipcRenderer.invoke('new-document'),
  switchTab: payload => ipcRenderer.invoke('switch-tab', payload),
  closeTab: payload => ipcRenderer.invoke('close-tab', payload),
  onTabs: callback => ipcRenderer.on('tabs', (_event, value) => callback(value)),
  onCloseTabRequest: callback => ipcRenderer.on('close-tab-request', () => callback()),
  onNextTabRequest: callback => ipcRenderer.on('next-tab-request', () => callback()),
  onPreviousTabRequest: callback => ipcRenderer.on('previous-tab-request', () => callback()),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  chooseSaveDirectory: () => ipcRenderer.invoke('choose-save-directory'),
  resetSaveDirectory: () => ipcRenderer.invoke('reset-save-directory'),
  drop: file => ipcRenderer.invoke('drop', webUtils.getPathForFile(file)),
  reload: () => ipcRenderer.invoke('reload-document'),
  external: href => ipcRenderer.invoke('external', href),
  copy: text => ipcRenderer.invoke('copy', text),
  onDocument: callback => ipcRenderer.on('document', (_event, result) => callback(result)),
  onToggleOutline: callback => ipcRenderer.on('toggle-outline', () => callback())
});
